apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "role-panel-bot.fullname" . }}-config
  labels:
    {{- include "role-panel-bot.labels" . | nindent 4 }}
data:
  log-level: {{ .Values.config.logLevel | quote }}
  health-port: {{ .Values.config.healthPort | quote }}
  db-max-connections: {{ .Values.config.databaseMaxConnections | quote }}
