{{- if not .Values.discord.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "role-panel-bot.discordSecretName" . }}
  labels:
    {{- include "role-panel-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  discord-token: {{ .Values.discord.token | quote }}
{{- end }}
---
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "role-panel-bot.databaseSecretName" . }}
  labels:
    {{- include "role-panel-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
