apiVersion: v1
kind: Service
metadata:
  name: {{ include "role-panel-bot.fullname" . }}
  labels:
    {{- include "role-panel-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "role-panel-bot.selectorLabels" . | nindent 4 }}
