apiVersion: v1
kind: Service
metadata:
  name: role-panel-bot
  labels:
    app: role-panel-bot
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
  selector:
    app: role-panel-bot
